/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1023267_6_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1023267_1[] = { "brzuszki", "idle", "pajacyki", "pompki", "run" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1023267_5_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1023267_5_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1023267_5 = {
    5, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    10.0f, // float filter-cutoff
    8, // int filter-order
    "FFT", // select analysis-type
    128, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "sym7", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1023267_5[93] = { 2.7631345525635416, 0.06210738009431681, 0.9227818492946029, 5.184769463845497, 29.935927626261446, 1.764827282978805, 1.5472009861692562, 1.2685391251204154, 1.148352465960428, 0.9841317946876789, 0.8638659294947246, 0.7800884279347584, 0.7058330773893516, 0.6220120145644836, 0.5308209744828011, 0.427014919938029, 0.36774830219711424, 0.2659905554390054, 0.2298785186663997, 0.1742678696046401, 0.10200807966566876, 0.010081444682139874, -0.05450633912223289, -0.11811444977002285, -0.17861070842348387, -0.2706723017865976, -0.37691502761037243, -0.5033119067594882, -0.6212218202394197, -0.7957993408210079, -0.8841745123596408, 4.623311152508392, 1.5353500038352113, 6.125530604281903, 4.783366249910281, 26.912365076991886, 2.13950138985185, 1.9726673069073055, 1.8049125245156323, 1.746970850885933, 1.5990769582082898, 1.4474847937840665, 1.3049042200640484, 1.1986174200846123, 1.1124168792849456, 1.0115037724626217, 0.9502421844921364, 0.9003353578707198, 0.8383346261865171, 0.8057701427737552, 0.7490821614806215, 0.6840701083730754, 0.5897500086441109, 0.5469087628809006, 0.4826041033307781, 0.4150287691859358, 0.3338899477938291, 0.21760360794569356, 0.05311657098398705, -0.11095813312377029, -0.39199097775805913, -0.4305176819452667, 2.426137058607361, 0.06898451150883879, 1.7298821482325732, 5.007254448869424, 28.306170960936065, 1.6104231595583254, 1.4615788763252335, 1.29417932305248, 1.16229404269031, 0.9000857869257654, 0.7883323138054523, 0.6762248352351085, 0.5422839461132144, 0.4427322542434967, 0.3568529145753637, 0.2714644965583643, 0.2353579547429347, 0.15236179921818593, 0.12201618498217594, 0.06692079184341257, 0.019332637361894202, -0.046448728297165426, -0.0795697720986714, -0.13458883175090372, -0.1995802355208809, -0.2707899819284535, -0.37146643031531035, -0.4929332365861366, -0.5944472690861237, -0.7712363996699955, -0.8642582840795708 };
const float ei_dn_standard_scaler_scale_1023267_5[93] = { 0.5521094204228871, 0.9381830376386743, 0.22285647151452087, 0.6955982930654445, 0.06792180371154694, 1.0780600601051655, 1.0855438954881016, 1.0977893669483814, 1.0059598059807533, 1.03362169459989, 1.0846781202959612, 1.0704163675903269, 1.0838233729567552, 1.0902547241405192, 1.0598583439467557, 1.04748020358752, 1.0512864433757207, 1.0481950772870916, 1.0336951566182981, 1.0122770986489424, 1.0020581682539103, 1.0066727387790122, 1.028889888077171, 1.0258708695883005, 1.054957344453737, 1.0690818205505355, 1.0699226105254092, 1.0546378412241202, 1.059334038903129, 1.034577430087571, 1.0633715265619428, 0.3193060193109062, 0.542454236349817, 0.09332007746727215, 0.539643076359866, 0.05901289963902861, 1.3101996136800855, 1.2338775029365487, 1.318082563751352, 1.1278452989326961, 1.1750769994162995, 1.378957063474368, 1.5093838793395604, 1.7456114994038148, 1.9085063885415803, 1.9776669448237296, 1.8902298032231075, 2.116251221429109, 2.2432322333396155, 2.224588620669271, 2.251895109876368, 2.313882230451629, 2.1745271711149865, 2.2922903028685884, 2.2698861975746243, 2.355626641705134, 2.3476270479452976, 2.274772644141214, 1.979122919790513, 1.8235619644726795, 1.4082852006789452, 1.5430845190479843, 0.5518234915418067, 0.7070043815174925, 0.14894063438351415, 0.6526942450520076, 0.0671720383501171, 1.3147791549408063, 1.1468860814422221, 1.0619290523816816, 1.013064125011023, 1.2200223896920919, 1.2729892510021432, 1.2473039245287805, 1.3559551626343627, 1.4328467940899208, 1.3991139333431413, 1.4175185046932766, 1.432126804718567, 1.4676450799470766, 1.5078074269563577, 1.5135907409492497, 1.4979336640117582, 1.4377978878039077, 1.4807411065031728, 1.4593013650123767, 1.4590257300816727, 1.4599731708323278, 1.4014885438647122, 1.3150846584822986, 1.2534830820854908, 1.1567922898653094, 1.2014858105315855 };
const float ei_dn_standard_scaler_var_1023267_5[93] = { 3.280572841318861, 1.1361216784496546, 20.134901060136638, 2.0667263888891134, 216.76121627414366, 0.8604271124506016, 0.8486042863782237, 0.8297780840052553, 0.9881861054115304, 0.9360019807070147, 0.8499595156195662, 0.8727593648785231, 0.8513006697717398, 0.8412867435742502, 0.8902343620139559, 0.9113985894523501, 0.90481100004435, 0.9101558575969968, 0.9358689469959083, 0.9758906941308961, 0.995896336877295, 0.9867869201776344, 0.9446310179717144, 0.9501990771433034, 0.898525072212454, 0.874939675838044, 0.8735650877093756, 0.89906957220483, 0.8911158023456863, 0.9342734351490712, 0.8843617401253202, 9.808120408802909, 3.3983944794526657, 114.82853358665709, 3.4338931797214265, 287.14819519293013, 0.5825390804334912, 0.6568344279294276, 0.5755920275988726, 0.7861418794249201, 0.7242147216265968, 0.5258943590729429, 0.4389353772135736, 0.3281744843851236, 0.2745445101619034, 0.2556781943658935, 0.27987930526317856, 0.223288088797315, 0.19872455193543814, 0.20206941179173415, 0.19719853506403662, 0.18677446374864826, 0.21148049718617393, 0.1903096303050958, 0.19408493741283567, 0.18021340194898453, 0.18144365716148397, 0.193252004008876, 0.25530214483730124, 0.3007176712985898, 0.5042184919647319, 0.4199722273085365, 3.2839733980279773, 2.000579385855648, 45.07893024628611, 2.34736396383212, 221.62714171819857, 0.578488034035538, 0.76025526354108, 0.8867659221701913, 0.9743749887714236, 0.6718377429435101, 0.617092867747173, 0.642769738968165, 0.5438878311448361, 0.48708021309643895, 0.5108505164438644, 0.4976712194054896, 0.48757008693875675, 0.46425641557720615, 0.4398536940233783, 0.43649882127002504, 0.4456714747191752, 0.48373144254470224, 0.45608074163079737, 0.4695804661306303, 0.4697579064630474, 0.4691484111923227, 0.5091208650188008, 0.5782192914657986, 0.6364481763811631, 0.7472901008469915, 0.6927279449778896 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1023267_5 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1023267_5,
    .mean_data_len = 93,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1023267_5,
    .scale_data_len = 93,
    .var_data = (float *)ei_dn_standard_scaler_var_1023267_5,
    .var_data_len = 93
};
ei_data_normalization_t ei_data_normalization_config_1023267_5 = {
    (void *) &ei_data_normalization_standard_scaler_config_1023267_5, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1023267_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1023267_1[ei_dsp_blocks_1023267_1_size] = {
    { // DSP block 5
        5,
        93, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1023267_5, // pointer to config struct
        ei_dsp_config_1023267_5_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1023267_5_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1023267_5, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1023267_6 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1023267_6_init,
    .model_invoke = &tflite_learn_1023267_6_invoke,
    .model_reset = &tflite_learn_1023267_6_reset,
    .model_input = &tflite_learn_1023267_6_input,
    .model_output = &tflite_learn_1023267_6_output,
};

const uint8_t ei_output_tensors_indices_1023267_6[1] = { 0 };
const uint8_t ei_output_tensors_size_1023267_6 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1023267_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .output_tensors_indices = ei_output_tensors_indices_1023267_6,
    .output_tensors_size = ei_output_tensors_size_1023267_6,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1023267_6,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1023267_1_size = 1;
const uint32_t ei_learning_block_1023267_6_inputs[1] = { 5 };
const uint8_t ei_learning_block_1023267_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1023267_1[ei_learning_blocks_1023267_1_size] = {
    {
        6,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1023267_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1023267_6_inputs,
        ei_learning_block_1023267_6_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1023267_6 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1023267_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1023267_1[ei_postprocessing_blocks_1023267_1_size] = {
    {
        .block_id = 6,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1023267_6,
        .input_block_id = 6
    },
};

const uint8_t freeform_outputs_1023267_1_size = 0;

uint32_t *freeform_outputs_1023267_1 = nullptr;

const ei_impulse_t impulse_1023267_1 = {
    .project_id = 1023267,
    .project_owner = "Miedziak44",
    .project_name = "Wearable Fitness Tracker",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 93,
    .raw_sample_count = 150,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 150 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_1023267_1_size,
    .dsp_blocks = ei_dsp_blocks_1023267_1,

    .learning_blocks_size = ei_learning_blocks_1023267_1_size,
    .learning_blocks = ei_learning_blocks_1023267_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1023267_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1023267_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_ACCELEROMETER,
    .fusion_string = "accX + accY + accZ",
    .slice_size = (150/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 5,
    .categories = ei_classifier_inferencing_categories_1023267_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1023267_1_size,
    .freeform_outputs = freeform_outputs_1023267_1
};

ei_impulse_handle_t impulse_handle_1023267_1 = ei_impulse_handle_t( &impulse_1023267_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1023267_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1023267_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1023267_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1023267_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
